variables:
  DOCKERFILE: "Dockerfile_SpringBoot"
  IMAGE_NAME: "myserver"
  DB_PORT: "3306"
  DB_HOST_PORT: "3307"
  APP_PORT: "8088"

stages:
  - test_springboot
  - build_springboot_image
  - test_springboot_image
  - deploy_springboot

test_job:
  stage: test_springboot
  script:
    - echo "Running unit test"

build_image_job:
  stage: build_springboot_image
  script:
    - echo "Building docker image"
    - ./mvnw clean package
    - docker build -t ${IMAGE_NAME}:$CI_COMMIT_REF_NAME -t ${IMAGE_NAME}:latest -f ${DOCKERFILE}

test_image_job:
  stage: test_springboot_image
  script:
    - echo "Running docker image to test"
    - docker run -p ${APP_PORT}:${APP_PORT} -p ${DB_HOST_PORT}:${DB_PORT} ${IMAGE_NAME}:$CI_COMMIT_REF_NAME --name ${IMAGE_NAME}_CICD

deploy_job:
  stage: deploy_springboot
  script:
    - echo "Deploying application"
